server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
  instance:
    hostname: https://eureka-rajureddy-konga-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    prefer-ip-address: true
